-- ========================================================
-- SCHEMA FOR TARGET DATABASE egvcinsbyropumybatdf
-- ========================================================

CREATE TABLE IF NOT EXISTS public.crm_inversionistas (
    tipo_doc VARCHAR(20) NOT NULL,
    documento_identidad VARCHAR(20) NOT NULL,
    nombre_1 VARCHAR(100) NOT NULL,
    nombre_2 VARCHAR(100) NULL,
    apellido_1 VARCHAR(100) NOT NULL,
    apellido_2 VARCHAR(100) NULL,
    nombre_completo VARCHAR(400) NULL,
    fecha_nacimiento DATE NULL,
    estado_civil VARCHAR(50) NULL,
    nacionalidad VARCHAR(100) NULL DEFAULT 'Perú'::character varying,
    residente_peru BOOLEAN NULL DEFAULT true,
    email VARCHAR(200) NULL,
    telefono VARCHAR(50) NULL,
    direccion_fiscal TEXT NULL,
    codigo_postal VARCHAR(20) NULL,
    conyuge_nombre_1 VARCHAR(100) NULL,
    conyuge_nombre_2 VARCHAR(100) NULL,
    conyuge_apellido_1 VARCHAR(100) NULL,
    conyuge_apellido_2 VARCHAR(100) NULL,
    conyuge_tipo_documento VARCHAR(20) NULL,
    conyuge_num_documento VARCHAR(20) NULL,
    ocupacion VARCHAR(200) NULL,
    centro_labores VARCHAR(200) NULL,
    cargo_ocupado VARCHAR(200) NULL,
    antiguedad_laboral_anios INTEGER NULL,
    es_pep BOOLEAN NULL DEFAULT false,
    pep_detalle TEXT NULL,
    perfil_riesgo VARCHAR(50) NULL DEFAULT 'Bajo'::character varying,
    estado_compliance VARCHAR(20) NULL DEFAULT 'borrador'::character varying,
    fecha_solicitud_compliance TIMESTAMP WITH TIME ZONE NULL,
    firma_oficial_json JSONB NULL DEFAULT '{}'::jsonb,
    observaciones_compliance TEXT NULL,
    codigo_inversionista VARCHAR(50) NOT NULL,
    fecha_aprobacion_compliance TIMESTAMP WITH TIME ZONE NULL,
    banco_nombre_pen VARCHAR(200) NULL,
    numero_cuenta_pen VARCHAR(100) NULL,
    cci_pen VARCHAR(100) NULL,
    banco_nombre_usd VARCHAR(200) NULL,
    numero_cuenta_usd VARCHAR(100) NULL,
    cci_usd VARCHAR(100) NULL,
    CONSTRAINT crm_inversionistas_pkey PRIMARY KEY (codigo_inversionista)
);

CREATE TABLE IF NOT EXISTS public.crm_asesores (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    codigo VARCHAR(50) NOT NULL,
    tipo_documento_asesor VARCHAR(20) NOT NULL,
    num_documento_asesor VARCHAR(20) NOT NULL,
    nombre_completo VARCHAR(200) NOT NULL,
    apellido_1 VARCHAR(100) NULL,
    apellido_materno_asesor VARCHAR(100) NULL,
    nombre_1 VARCHAR(100) NULL,
    fecha_nacimiento_asesor DATE NULL,
    estado_civil_asesor VARCHAR(50) NULL,
    profesion_asesor VARCHAR(100) NULL,
    nacionalidad_asesor VARCHAR(50) NULL,
    direccion_asesor TEXT NULL,
    distrito_asesor VARCHAR(100) NULL,
    provincia_asesor VARCHAR(100) NULL,
    departamento_asesor VARCHAR(100) NULL,
    pais_residencia_asesor VARCHAR(100) NULL,
    email VARCHAR(150) NULL,
    telefono VARCHAR(50) NULL,
    nombre_completo_conyuge_asesor VARCHAR(200) NULL,
    tipo_documento_conyuge_asesor VARCHAR(20) NULL,
    num_documento_conyuge_asesor VARCHAR(20) NULL,
    ocupacion_asesor VARCHAR(100) NULL,
    centro_labores_asesor VARCHAR(150) NULL,
    cargo_ocupado_asesor VARCHAR(100) NULL,
    es_pep_asesor BOOLEAN NULL DEFAULT false,
    pep_detalle_asesor TEXT NULL,
    banco_nombre_pen VARCHAR(100) NULL,
    numero_cuenta_pen VARCHAR(50) NULL,
    cci_pen VARCHAR(50) NULL,
    banco_nombre_usd VARCHAR(100) NULL,
    numero_cuenta_usd VARCHAR(50) NULL,
    cci_usd VARCHAR(50) NULL,
    estado_compliance VARCHAR(20) NULL DEFAULT 'pendiente'::character varying,
    sello_oficial_cumplimiento JSONB NULL,
    updated_at TIMESTAMP WITH TIME ZONE NULL,
    codigo_postal_asesor VARCHAR(20) NULL,
    antiguedad_laboral_anios_asesor NUMERIC NULL,
    CONSTRAINT crm_asesores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.crm_fondos (
    created_at TIMESTAMP WITH TIME ZONE NULL DEFAULT now(),
    nombre_fondo TEXT NOT NULL,
    id_fondo TEXT NOT NULL,
    moneda TEXT NULL,
    plazo_inversion TEXT NULL,
    tasa NUMERIC NULL,
    vigencia_tasa INTEGER NULL,
    plazo_rescate_meses INTEGER NULL,
    plazo_opcion_de_rescate_dias INTEGER NULL,
    penalidad_rescate NUMERIC NULL,
    tamanho_maximo_fondo NUMERIC NULL,
    monto_minimo_inversion NUMERIC NULL,
    valor_cuota_inicial NUMERIC NULL,
    activo TEXT NULL DEFAULT 'SI'::text,
    comision_administracion_fondo NUMERIC NULL,
    comision_captacion_fondo NUMERIC NULL,
    frecuencia_cupones_meses INTEGER NULL DEFAULT 1,
    ruc_fondo TEXT NULL,
    fecha_cierre_fondo DATE NULL,
    tasa_activa NUMERIC NULL DEFAULT 0.0,
    comision_miscelaneos_fondo NUMERIC NULL DEFAULT 0.0,
    comision_asesor_unica NUMERIC NULL DEFAULT 0.0,
    comision_asesor_primer_ano NUMERIC NULL DEFAULT 0.0,
    comision_asesor_mantenimiento NUMERIC NULL DEFAULT 0.0,
    id_fondo_plazo TEXT NOT NULL,
    CONSTRAINT crm_fondos_pkey PRIMARY KEY (id_fondo_plazo)
);

CREATE TABLE IF NOT EXISTS public.crm_contratos (
    id_contrato TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    id_inversionista_1 TEXT NULL,
    id_inversionista_2 TEXT NULL,
    id_inversionista_3 TEXT NULL,
    id_inversionista_4 TEXT NULL,
    id_fondo TEXT NULL,
    id_asesor TEXT NULL,
    porcentaje_participacion_1 NUMERIC NULL DEFAULT 0,
    porcentaje_participacion_2 NUMERIC NULL DEFAULT 0,
    porcentaje_participacion_3 NUMERIC NULL DEFAULT 0,
    porcentaje_participacion_4 NUMERIC NULL DEFAULT 0,
    porcentaje_deposito_1 NUMERIC NULL DEFAULT 0,
    porcentaje_deposito_2 NUMERIC NULL DEFAULT 0,
    porcentaje_deposito_3 NUMERIC NULL DEFAULT 0,
    porcentaje_deposito_4 NUMERIC NULL DEFAULT 0,
    porcentaje_reparto NUMERIC NULL DEFAULT 100,
    monto_inversion NUMERIC NOT NULL DEFAULT 0,
    moneda VARCHAR(3) NOT NULL,
    plazo_meses TEXT NULL,
    tasa_pactada NUMERIC NOT NULL DEFAULT 0,
    frecuencia_cupones_meses INTEGER NOT NULL DEFAULT 3,
    fecha_inicio DATE NULL,
    fecha_fin DATE NULL,
    domicilio_contractual TEXT NULL,
    voucher_deposito_url TEXT NULL,
    contrato_firmado_url TEXT NULL,
    estado VARCHAR(20) NULL DEFAULT 'borrador'::character varying,
    id_fondo_plazo TEXT NULL,
    CONSTRAINT crm_contratos_pkey PRIMARY KEY (id_contrato)
);

CREATE TABLE IF NOT EXISTS public.crm_certificados (
    id_certificado TEXT PRIMARY KEY,
    id_contrato TEXT NOT NULL REFERENCES crm_contratos(id_contrato) ON DELETE CASCADE,
    fecha_emision DATE NOT NULL DEFAULT CURRENT_DATE,
    monto_inversion NUMERIC(20, 2) NOT NULL,
    valor_cuota NUMERIC(20, 4) NOT NULL,
    numero_cuotas NUMERIC(20, 4) NOT NULL,
    titulares_resumen JSONB NULL DEFAULT '[]'::jsonb,
    estado TEXT DEFAULT 'emitido',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.crm_certificados_eventos (
    id_certificado VARCHAR(255) NOT NULL,
    id_certificado_origen VARCHAR(255) NOT NULL,
    id_contrato VARCHAR(255) NOT NULL,
    tipo_evento VARCHAR(50) NOT NULL,
    fecha_periodo_origen DATE NOT NULL,
    fecha_periodo_fin DATE NOT NULL,
    capital_base NUMERIC NULL DEFAULT 0.00,
    interes_generado_bruto NUMERIC NULL DEFAULT 0.00,
    impuestos_renta NUMERIC NULL DEFAULT 0.00,
    interes_neto_disponible NUMERIC NULL DEFAULT 0.00,
    monto_deduccion NUMERIC NULL DEFAULT 0.00,
    monto_capitalizacion NUMERIC NULL DEFAULT 0.00,
    monto_reparto NUMERIC NULL DEFAULT 0.00,
    monto_rescate NUMERIC NULL DEFAULT 0.00,
    penalidad_rescate NUMERIC NULL DEFAULT 0.00,
    capital_final_saldo NUMERIC NULL DEFAULT 0.00,
    estado_pago VARCHAR(50) NULL DEFAULT 'no_aplica'::character varying,
    fecha_pago_real DATE NULL,
    comprobante_banco VARCHAR(255) NULL,
    id_deduccion_rescate UUID NULL,
    dias_calculados INTEGER NULL DEFAULT 0,
    tasa_aplicada NUMERIC NULL DEFAULT 0.0000,
    pct_reparto_aplicado NUMERIC NULL DEFAULT 0.0000,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
    notas TEXT NULL,
    id_evento INTEGER NOT NULL,
    payload_asiento JSONB NULL,
    CONSTRAINT crm_certificados_eventos_pkey PRIMARY KEY (id_evento)
);

CREATE TABLE IF NOT EXISTS public.crm_cronograma_deducciones_rescates (
    id_cuota TEXT NOT NULL,
    id_agrupador TEXT NOT NULL,
    id_certificado VARCHAR(100) NOT NULL,
    id_contrato VARCHAR(100) NOT NULL,
    tipo_cargo VARCHAR(50) NOT NULL,
    glosa_descripcion TEXT NULL,
    moneda VARCHAR(3) NOT NULL,
    monto_cobrar NUMERIC NOT NULL,
    fecha_proyectada_cobro DATE NOT NULL,
    estado VARCHAR(50) NOT NULL DEFAULT 'PENDIENTE'::character varying,
    prioridad INTEGER NOT NULL DEFAULT 1,
    id_evento_ledger TEXT NULL,
    creado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    creado_por TEXT NULL,
    tasa NUMERIC NULL DEFAULT 0,
    CONSTRAINT crm_cronograma_deducciones_rescates_pkey PRIMARY KEY (id_cuota)
);
